# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0012_auto_20151221_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='kind',
            field=models.CharField(choices=[(b'nfc', b'NFC'), (b'mac', b'MAC'), (b'tag', b'TAG')], default=b'nfc', max_length=3),
        ),
    ]
